// import Header from './Header';
// import Footer from './Footer';

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
const RootLayout = ({ children }) => {
  return (
    <>
      {/* <Header /> */}
      <p>header from components lauout</p>
      <main>{children}</main>
      {/* <Footer /> */}
    </>
  );
};

export default RootLayout;